[tool.poetry]
name = "cw-development"
version = "0.1.0"
description = ""
authors = ["Eugene Rudnev <larsoid@yandex.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
